# Generated by Django 5.2.7 on 2025-12-23 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_component', models.BooleanField(default=False, help_text='Đánh dấu nếu đây là linh kiện có thể tách rời khỏi thiết bị (RAM, SSD, Card màn hình)')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('asset_code', models.CharField(max_length=100, unique=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('status', models.CharField(choices=[('in_use', 'Đang sử dụng'), ('in_storage', 'Lưu kho'), ('liquidated', 'Thanh lý'), ('broken', 'Hư hỏng')], default='in_storage', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('acquisition_type', models.CharField(choices=[('purchase', 'Mua sắm'), ('transfer', 'Điều chuyển'), ('donation', 'Tiếp nhận')], max_length=50)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('has_independent_value', models.BooleanField(default=True, help_text='True nếu tài sản có giá trị độc lập cần đối soát với kế toán')),
                ('serial_number', models.CharField(blank=True, help_text='Số serial của thiết bị', max_length=100)),
                ('model', models.CharField(blank=True, help_text='Model thiết bị', max_length=100)),
                ('vendor', models.CharField(blank=True, help_text='Nhà cung cấp, phân phối', max_length=255)),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text='Giá trị tài sản (VNĐ)', max_digits=15, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent_asset', models.ForeignKey(blank=True, help_text='Chỉ định tài sản cấp trên (Ví dụ: RAM thuộc về Máy tính nào)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='main.asset')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.assetcategory')),
                ('current_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.department')),
                ('location', models.ForeignKey(blank=True, help_text='Vị trí hiện tại của tài sản', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.location')),
            ],
        ),
        migrations.CreateModel(
            name='AssetAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='asset_attachments/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='main.asset')),
            ],
        ),
        migrations.CreateModel(
            name='AssetAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('in_use', 'Đang sử dụng'), ('in_storage', 'Lưu kho'), ('liquidated', 'Thanh lý'), ('broken', 'Hư hỏng')], max_length=20)),
                ('is_matching', models.BooleanField()),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.asset')),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('physical_location', models.ForeignKey(help_text='Vị trí thực tế khi kiểm kê', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.location')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.department')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='current_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.person'),
        ),
        migrations.CreateModel(
            name='TicketRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('repair', 'Sửa chữa'), ('borrow', 'Mượn tài sản'), ('maintenance', 'Bảo trì')], default='repair', max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('in_progress', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('rejected', 'Từ chối')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('scheduled_date', models.DateField(blank=True, help_text='Ngày dự kiến thực hiện', null=True)),
                ('frequency', models.CharField(blank=True, choices=[('monthly', 'Hàng tháng'), ('quarterly', 'Hàng quý'), ('semi_annual', '6 tháng'), ('annual', 'Hàng năm')], help_text='Tần suất bảo trì', max_length=20, null=True)),
                ('is_recurring', models.BooleanField(default=False, help_text='Là yêu cầu bảo trì định kỳ')),
                ('next_maintenance_date', models.DateField(blank=True, help_text='Ngày bảo trì tiếp theo', null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.asset')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_tickets', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('transfer', 'Bàn giao'), ('repair', 'Sửa chữa'), ('borrow', 'Cho mượn'), ('maintenance', 'Bảo trì'), ('upgrade', 'Nâng cấp'), ('retrieve', 'Thu hồi'), ('create', 'Tạo mới'), ('update', 'Cập nhật thông tin'), ('audit', 'Kiểm kê'), ('status_change', 'Thay đổi trạng thái'), ('location_change', 'Thay đổi vị trí')], default='transfer', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('from_status', models.CharField(blank=True, choices=[('in_use', 'Đang sử dụng'), ('in_storage', 'Lưu kho'), ('liquidated', 'Thanh lý'), ('broken', 'Hư hỏng')], max_length=20, null=True)),
                ('to_status', models.CharField(blank=True, choices=[('in_use', 'Đang sử dụng'), ('in_storage', 'Lưu kho'), ('liquidated', 'Thanh lý'), ('broken', 'Hư hỏng')], max_length=20, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='main.asset')),
                ('related_audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.assetaudit')),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_histories', to='main.department')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_histories', to='main.department')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_histories', to='main.location')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_histories', to='main.location')),
                ('from_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_person_histories', to='main.person')),
                ('to_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_person_histories', to='main.person')),
                ('related_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ticketrequest')),
            ],
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_code'], name='main_asset_asset_c_b12783_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['category'], name='main_asset_categor_15a656_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['current_department'], name='main_asset_current_7276c0_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['location'], name='main_asset_locatio_62a14f_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status'], name='main_asset_status_650c70_idx'),
        ),
    ]
