# Generated by Django 5.2.7 on 2026-01-06 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_status', models.CharField(blank=True, choices=[('in_use', 'Đang sử dụng'), ('in_storage', 'Lưu kho'), ('liquidated', 'Thanh lý'), ('broken', 'Hư hỏng')], help_text='Trạng thái theo hệ thống', max_length=20, null=True)),
                ('actual_status', models.CharField(blank=True, choices=[('in_use', 'Đang sử dụng'), ('in_storage', 'Lưu kho'), ('liquidated', 'Thanh lý'), ('broken', 'Hư hỏng')], help_text='Trạng thái thực tế', max_length=20, null=True)),
                ('result_status', models.CharField(choices=[('pending', 'Chưa kiểm kê'), ('matched', 'Khớp'), ('location_mismatch', 'Sai vị trí'), ('status_mismatch', 'Sai trạng thái'), ('person_mismatch', 'Sai người quản lý'), ('missing', 'Không tìm thấy'), ('damaged', 'Hư hỏng phát hiện'), ('excess', 'Thừa (không có trong hệ thống)')], default='pending', help_text='Kết quả kiểm kê', max_length=30)),
                ('audited_at', models.DateTimeField(blank=True, help_text='Thời điểm kiểm kê', null=True)),
                ('notes', models.TextField(blank=True, help_text='Ghi chú chênh lệch, mô tả')),
                ('photo', models.ImageField(blank=True, help_text='Ảnh chụp thực tế', upload_to='audit_photos/')),
                ('scanned_code', models.CharField(blank=True, help_text='Mã quét được từ QR/Barcode', max_length=100)),
                ('scan_method', models.CharField(choices=[('manual', 'Nhập thủ công'), ('qr', 'Quét mã QR'), ('barcode', 'Quét Barcode')], default='manual', help_text='Phương thức nhập liệu', max_length=20)),
                ('actual_location', models.ForeignKey(blank=True, help_text='Vị trí thực tế', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_audit_items', to='main.location')),
                ('actual_person', models.ForeignKey(blank=True, help_text='Người đang giữ thực tế', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_audit_items', to='main.person')),
                ('asset', models.ForeignKey(blank=True, help_text='Tài sản cần kiểm kê', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_items', to='main.asset')),
                ('auditor', models.ForeignKey(blank=True, help_text='Người thực hiện kiểm kê', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_items', to=settings.AUTH_USER_MODEL)),
                ('expected_department', models.ForeignKey(blank=True, help_text='Phòng ban theo hệ thống', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expected_audit_items', to='main.department')),
                ('expected_location', models.ForeignKey(blank=True, help_text='Vị trí theo hệ thống', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expected_audit_items', to='main.location')),
                ('expected_person', models.ForeignKey(blank=True, help_text='Người quản lý theo hệ thống', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expected_audit_items', to='main.person')),
            ],
            options={
                'verbose_name': 'Chi tiết kiểm kê',
                'verbose_name_plural': 'Chi tiết kiểm kê',
                'ordering': ['audit_session', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AuditAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('update_location', 'Cập nhật vị trí'), ('update_status', 'Cập nhật trạng thái'), ('update_person', 'Cập nhật người quản lý'), ('report_missing', 'Báo mất'), ('repair', 'Sửa chữa'), ('liquidate', 'Thanh lý'), ('compensate', 'Yêu cầu bồi thường'), ('create_new', 'Tạo mới (tài sản thừa)'), ('no_action', 'Không cần xử lý')], help_text='Loại đề xuất xử lý', max_length=30)),
                ('description', models.TextField(help_text='Mô tả chi tiết đề xuất')),
                ('status', models.CharField(choices=[('proposed', 'Đề xuất'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('executed', 'Đã thực hiện')], default='proposed', max_length=20)),
                ('proposed_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_note', models.TextField(blank=True, help_text='Lý do từ chối')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Người duyệt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('executed_by', models.ForeignKey(blank=True, help_text='Người thực hiện', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('proposed_by', models.ForeignKey(help_text='Người đề xuất', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('result_history', models.ForeignKey(blank=True, help_text='Lịch sử tài sản được tạo từ đề xuất này', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_audit_actions', to='main.assethistory')),
                ('result_ticket', models.ForeignKey(blank=True, help_text='Ticket được tạo từ đề xuất này', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_audit_actions', to='main.ticketrequest')),
                ('audit_item', models.ForeignKey(help_text='Chi tiết kiểm kê liên quan', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='main.audititem')),
            ],
            options={
                'verbose_name': 'Đề xuất xử lý kiểm kê',
                'verbose_name_plural': 'Các đề xuất xử lý kiểm kê',
                'ordering': ['-proposed_at'],
            },
        ),
        migrations.AlterField(
            model_name='assethistory',
            name='related_audit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.audititem'),
        ),
        migrations.CreateModel(
            name='AuditSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Mã đợt kiểm kê (VD: KK-2026-Q1)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Tên đợt kiểm kê', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Mô tả chi tiết')),
                ('scope', models.CharField(choices=[('full', 'Toàn bộ tài sản'), ('department', 'Theo phòng ban'), ('location', 'Theo vị trí'), ('category', 'Theo loại tài sản'), ('custom', 'Tùy chọn (chọn thủ công)')], default='full', help_text='Phạm vi kiểm kê', max_length=20)),
                ('planned_start_date', models.DateField(help_text='Ngày bắt đầu dự kiến')),
                ('planned_end_date', models.DateField(help_text='Ngày kết thúc dự kiến')),
                ('actual_start_date', models.DateField(blank=True, help_text='Ngày bắt đầu thực tế', null=True)),
                ('actual_end_date', models.DateField(blank=True, help_text='Ngày kết thúc thực tế', null=True)),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('planned', 'Đã lên kế hoạch'), ('in_progress', 'Đang thực hiện'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_assets', models.IntegerField(default=0, help_text='Tổng số tài sản cần kiểm kê')),
                ('checked_assets', models.IntegerField(default=0, help_text='Số tài sản đã kiểm kê')),
                ('matched_assets', models.IntegerField(default=0, help_text='Số tài sản khớp')),
                ('mismatched_assets', models.IntegerField(default=0, help_text='Số tài sản chênh lệch')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Người duyệt kế hoạch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_audit_sessions', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, help_text='Loại tài sản cần kiểm kê (khi scope=category)', related_name='audit_sessions', to='main.assetcategory')),
                ('created_by', models.ForeignKey(help_text='Người tạo đợt kiểm kê', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_audit_sessions', to=settings.AUTH_USER_MODEL)),
                ('departments', models.ManyToManyField(blank=True, help_text='Phòng ban cần kiểm kê (khi scope=department)', related_name='audit_sessions', to='main.department')),
                ('locations', models.ManyToManyField(blank=True, help_text='Vị trí cần kiểm kê (khi scope=location)', related_name='audit_sessions', to='main.location')),
            ],
            options={
                'verbose_name': 'Đợt kiểm kê',
                'verbose_name_plural': 'Các đợt kiểm kê',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='audititem',
            name='audit_session',
            field=models.ForeignKey(help_text='Đợt kiểm kê', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.auditsession'),
        ),
        migrations.DeleteModel(
            name='AssetAudit',
        ),
        migrations.AlterUniqueTogether(
            name='audititem',
            unique_together={('audit_session', 'asset')},
        ),
        migrations.CreateModel(
            name='AssetAudit',
            fields=[
            ],
            options={
                'verbose_name': '[Deprecated] Kiểm kê cũ',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.audititem',),
        ),
    ]
