# Generated by Django 5.2.7 on 2026-01-06 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_audititem_auditaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='value',
        ),
        migrations.AddField(
            model_name='asset',
            name='accounting_code',
            field=models.CharField(blank=True, help_text='Số hiệu tài sản kế toán', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='country_of_origin',
            field=models.CharField(blank=True, help_text='Nước sản xuất', max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='depreciation_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tỷ lệ khấu hao (%/năm)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='internal_code',
            field=models.CharField(blank=True, help_text='Ký hiệu nội bộ', max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='manufacturing_year',
            field=models.PositiveIntegerField(blank=True, help_text='Năm sản xuất', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='original_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nguyên giá (VNĐ)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='part_number',
            field=models.CharField(blank=True, help_text='Mã linh kiện (Part Number)', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Số lượng'),
        ),
        migrations.AddField(
            model_name='asset',
            name='unit',
            field=models.CharField(choices=[('cái', 'Cái'), ('bộ', 'Bộ'), ('chiếc', 'Chiếc'), ('máy', 'Máy'), ('thanh', 'Thanh'), ('hộp', 'Hộp')], default='cái', help_text='Đơn vị tính', max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='useful_life_years',
            field=models.PositiveIntegerField(blank=True, help_text='Số năm sử dụng (thời gian khấu hao)', null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='acquisition_date',
            field=models.DateField(blank=True, help_text='Ngày đưa vào sử dụng', null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='acquisition_type',
            field=models.CharField(choices=[('purchase', 'Mua sắm'), ('transfer', 'Điều chuyển nội bộ'), ('donation', 'Tiếp nhận/Tặng'), ('grant', 'Cấp phát'), ('project', 'Dự án đầu tư')], default='purchase', help_text='Hình thức tiếp nhận', max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_code',
            field=models.CharField(help_text='Mã tài sản', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='has_independent_value',
            field=models.BooleanField(default=True, help_text='Có giá trị độc lập cần đối soát kế toán'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Vị trí hiện tại', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.location'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(help_text='Tên tài sản', max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='note',
            field=models.TextField(blank=True, help_text='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='parent_asset',
            field=models.ForeignKey(blank=True, help_text='Tài sản cấp trên (VD: RAM thuộc Máy tính nào)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='main.asset'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(blank=True, help_text='Ngày mua sắm', null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Số serial', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='vendor',
            field=models.CharField(blank=True, help_text='Nhà cung cấp/Nhãn hiệu', max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='warranty_expiry',
            field=models.DateField(blank=True, help_text='Hạn bảo hành', null=True),
        ),
        migrations.AlterField(
            model_name='assethistory',
            name='action',
            field=models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật thông tin'), ('split', 'Tách tài sản'), ('transfer', 'Bàn giao'), ('location_change', 'Thay đổi vị trí'), ('status_change', 'Thay đổi trạng thái'), ('borrow', 'Cho mượn'), ('return', 'Trả lại'), ('upgrade', 'Nâng cấp/Lắp thêm'), ('retrieve', 'Thu hồi/Tháo ra'), ('repair', 'Sửa chữa'), ('maintenance', 'Bảo trì'), ('audit', 'Kiểm kê')], default='transfer', max_length=20),
        ),
    ]
